framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    http_method_override: true
    session:
        handler_id:  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        cookie_lifetime : 0
    #esi: true
    #fragments: true
    php_errors:
        log: true
    validation:
        enable_annotations: true
