c975_l_contact_form:
    site: 'Sandbox.975L.com'
    sentTo: 'sandbox@975l.com'
    database: true

c975_l_email:
    sentFrom: 'sandbox@975l.com'
    roleNeeded: 'ROLE_ADMIN'

c975_l_events:
    roleNeeded: 'ROLE_ADMIN'
    folderPictures: 'events'
    sitemapBaseUrl: 'http://sandbox.975l.com'
    tinymceLanguage: 'fr_FR'

c975_l_gift_voucher:
    live: false
    roleNeeded: 'ROLE_ADMIN'
    tosUrl: 'pageedit_display, {page: terms-of-sales}'
    tosPdf: 'pageedit_pdf, {page: terms-of-sales}'
    defaultCurrency: 'EUR'
    proposedCurrencies: ['EUR']

c975_l_page_edit:
    folderPages: 'pages'
    roleNeeded: 'ROLE_ADMIN'
    sitemapBaseUrl: 'http://sandbox.975l.com'
    sitemapLanguages: ['en', 'fr', 'es']
    tinymceLanguage: 'fr_FR'

c975_l_payment:
    site: 'Sandbox.975l.com'
    live: false
    timezone: 'Europe/Paris'
    database: true
    image: 'images/og-image.png'

c975_l_purchase_credits:
    creditsNumber: [1, 2, 3, 4, 5, 25, 50 ]
    creditsPrice: [ 1, 2, 3, 4, 5, 22.5, 40 ]
    currency: 'EUR'
    live: false
    userEntity: 'AppBundle\Entity\User'
    roleNeeded: 'ROLE_ADMIN'
    tosUrl: "pageedit_display, {page: terms-of-sales}"
    tosPdf: "pageedit_pdf, {page: terms-of-sales}"

c975_l_user:
    site: 'Sandbox.975l.com'
    roleNeeded: 'ROLE_ADMIN'
    touUrl: "pageedit_display, {page: terms-of-use}"
    signinAttempts: 5
    avatar: true
    signup: true
    hwiOauth: ['facebook', 'google', 'live']
    social: true
    databaseEmail: true
    archiveUser: true
    business: true
    multilingual: {'English': 'en', 'Français': 'fr', 'Español': 'es'}
    entity: 'AppBundle\Entity\User'
    signupForm: 'AppBundle\Form\UserSignupType'

c975_l_exception_checker:
    roleNeeded: 'ROLE_ADMIN'
    redirectExcluded: 'pageedit_home'