# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       [ROLE_MODERATOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATOR, ROLE_USER]
    providers:
        c975_l_userbundle:
            entity:
                class: AppBundle\Entity\User
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|fonts|images|js)/
            security: false
        main:
            pattern: ^/
            provider: c975_l_userbundle
            form_login:
                login_path: user_signin
                check_path: user_signin
                default_target_path: user_dashboard
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret: '%secret%'
                lifetime: 31536000
                path: /
                secure: true
            oauth:
                resource_owners:
                    facebook: "/login/facebook"
                    google: "/login/google"
                    live: "/login/live"
                login_path: user_signin
                failure_path: user_signin
                use_forward: true
                default_target_path: user_dashboard
                oauth_user_provider:
                    service: c975L\UserBundle\Security\OAuthUserProvider
            anonymous:    true
            logout_on_user_change: true
            logout:
                path: user_signout
                handlers: [c975L\UserBundle\Listener\LogoutListener]
    access_control:
