services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true
    Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler:
        public: false
        arguments:
            - 'mysql:host=%database_host%;port=%database_port%;dbname=%database_name%'
            - { db_username: '%database_user%', db_password: '%database_password%' }

    AppBundle\Command\:
        resource: '../../src/AppBundle/Command/*'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller/*'

    AppBundle\Form\:
        resource: '../../src/AppBundle/Form/*'

    AppBundle\Listener\:
        resource: '../../src/AppBundle/Listener/*'

    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension
    twig.intl_extension:
        class: Twig_Extensions_Extension_Intl
        tags:
            - name: twig.extension

    c975L\UserBundle\Security\OAuthUserProvider:
        public: true