<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    c975L\ToolbarBundle\c975LToolbarBundle::class => ['all' => true],
    c975L\ConfigBundle\c975LConfigBundle::class => ['all' => true],
    c975L\ServicesBundle\c975LServicesBundle::class => ['all' => true],
    c975L\IncludeLibraryBundle\c975LIncludeLibraryBundle::class => ['all' => true],
    Knp\Bundle\PaginatorBundle\KnpPaginatorBundle::class => ['all' => true],
    c975L\EmailBundle\c975LEmailBundle::class => ['all' => true],
    c975L\ContactFormBundle\c975LContactFormBundle::class => ['all' => true],
    c975L\ExceptionCheckerBundle\c975LExceptionCheckerBundle::class => ['all' => true],
    Knp\Bundle\SnappyBundle\KnpSnappyBundle::class => ['all' => true],
    c975L\PageEditBundle\c975LPageEditBundle::class => ['all' => true],
    c975L\PaymentBundle\c975LPaymentBundle::class => ['all' => true],
    c975L\SiteBundle\c975LSiteBundle::class => ['all' => true],
    Misd\PhoneNumberBundle\MisdPhoneNumberBundle::class => ['all' => true],
    c975L\UserBundle\c975LUserBundle::class => ['all' => true],
    c975L\CountLinesCodeBundle\c975LCountLinesCodeBundle::class => ['dev' => true, 'test' => true],
    c975L\XliffBundle\c975LXliffBundle::class => ['dev' => true, 'test' => true],
    c975L\PurchaseCreditsBundle\c975LPurchaseCreditsBundle::class => ['all' => true],
];
